# Generated by Django 5.2.7 on 2025-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmodel',
            name='username',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
