# Generated by Django 5.2.7 on 2025-12-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0002_authmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmodel',
            name='role',
            field=models.CharField(default='no role yet', max_length=20),
            preserve_default=False,
        ),
    ]
