# Generated by Django 5.2.7 on 2025-12-28 18:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0003_authmodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('ISBN', models.CharField(max_length=20)),
                ('pbulisher', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='LBRY/books')),
            ],
        ),
    ]
