# Generated by Django 5.2.7 on 2025-12-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0004_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('home_address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='home_address',
        ),
    ]
