# Generated by Django 5.2.7 on 2025-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0006_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='image',
            new_name='cover_imge',
        ),
        migrations.AddField(
            model_name='books',
            name='copies',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.IntegerField(),
        ),
    ]
