# Generated by Django 5.2.7 on 2025-12-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0007_rename_image_books_cover_imge_books_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(max_length=20),
        ),
    ]
