# Generated by Django 5.2.7 on 2025-12-30 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0008_alter_books_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='cover_imge',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='authmodel',
            name='username',
        ),
        migrations.RemoveField(
            model_name='books',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='books',
            name='pbulisher',
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_id', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_copies', to='LYMSApp.books')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(default=django.utils.timezone.now)),
                ('due_at', models.DateField()),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('renewed_times', models.PositiveIntegerField(default=0)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LYMSApp.bookcopy')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LYMSApp.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('copy',), name='one_active_issue_per_copy')],
            },
        ),
    ]
