# Generated by Django 5.2.7 on 2026-01-04 19:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0009_rename_cover_imge_books_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='LBRY'),
        ),
    ]
