# Generated by Django 5.2.7 on 2026-01-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0010_alter_books_cover_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authmodel',
            managers=[
            ],
        ),
    ]
