# Generated by Django 5.2.7 on 2026-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYMSApp', '0012_alter_books_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
